version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # For RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: tuyenga
      RABBITMQ_DEFAULT_PASS: s3cret

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pocket-pal
      POSTGRES_USER: tuyenga
      POSTGRES_PASSWORD: s3cret
